### ISSUE TITLE
New A1111 update interferes with this extension. 

### ISSUE THREAD

**Issue by AI-Casanova** [NoCrypt/sd-fast-pnginfo#1]
I love this extension, but it seems to lock the script box closed on the newest A1111

If you have XYZ plot open for instance, and send to txt2img, the script box will go to none, and when you go to reselect XYZ plot, it won't load.

**Comment by NoCrypt** [comment]
Hello, this seems to be a problem to A1111 Webui instead of this extension, since I'm just using buttons that is provided by webui

**Comment by AI-Casanova** [comment]
I would agree, except that the built-in works, and yours also seems to have odd behaviors with things like the hidden values of tenc and UNet weights for the additional networks extension (setting them inexplicably to -1 at times). 

I was wondering if you were pushing all values, even ones that do not appear in the metadata perhaps?

Such is the way of things with A1111 I guess, but I really wish your code was the native one. :)

**Comment by NoCrypt** [comment]
Seems fixed after few A1111 updates
