### ISSUE TITLE
FastPNG info fails if prompt contains chinese characters.

### ISSUE THREAD

**Issue by zcatharisis** [NoCrypt/sd-fast-pnginfo#6]
Title, happens regardless of whether it's part of the prompt, a lora filename, etc.

A1111's regular pnginfo is really slow so I hope this gets patched soon. Thanks for your work.

**Comment by gutris1** [comment]
> Title, happens regardless of whether it's part of the prompt, a lora filename, etc.
> 
> A1111's regular pnginfo is really slow so I hope this gets patched soon. Thanks for your work.

![Screenshot_3](https://github.com/NoCrypt/sd-fast-pnginfo/assets/132797949/0fc41ae3-2d95-4bfc-8dcb-785c58ed9874)
I fixed it
get it from here https://github.com/gutris1/sd-fast-pnginfo
if you dont want to wait.
